Script/CandySpawner.gd
Script/Goober.gd

https://docs.godotengine.org/en/stable/classes/class_%40globalscope.html#class-globalscope-method-randomize says:
> Note: This function is called automatically when the project is run.
https://docs.godotengine.org/en/stable/tutorials/math/random_number_generation.html#the-randomize-method says:
> Since Godot 4.0, the random seed is automatically set to a random value when
> the project starts. This means you don't need to call randomize() in _ready()
> anymore to ensure that results are random across project runs.
We do not need to repeatedly reseed the global RNG.

Remove unnecessary randomize() calls

---

Script/Game.gd
Script/Global.gd

Previously, the number of levels was hardcoded in the Global script, and would
have to match the number of scene files in the TileMap directory.
Instead, when Global is initialized, enumerate the numbered scene files in that
directory; sort them numerically; and load them for good measure. The number of
levels is then determined from the number of scenes found.
Fixes #5
Stacked on:
- #12

Count levels dynamically

---

project.godot

Practically speaking, this changes the window's title, and the name of the project in the Godot Editor project list.
Helps https://github.com/endlessm/everlasting-candy/issues/1

Retitle project to “Everlasting Candy”

---

Script/CandySpawner.gd

global.level, global.firstLevel, and global.lastLevel are all ints, so both sides of `(global.level - global.firstLevel) / (global.lastLevel - global.firstLevel)` are ints. So integer division is used, which rounds down. This means that, rather than the rate at which candies fall being a linear function of how far through the game you are, increasing in rate between one per 3 seconds and 3 per second, it actually stayed at one per 3 seconds throughout the game.
Use floating-point division instead by coercing the numerator to a float.

Fix increasingly fast spawning of candies

---

Scene/WorldSelector.tscn
Theme/WorldSelector.tres

I want to split up the world selector and it will be easier to have the theme
stored outside the scene.
There are no changes to the theme itself in this commit.

WorldSelector: Split theme to its own file

---

Audio/OST.mp3.import
Script/Global.gd

Previously, the OST was not set to loop; instead, a signal handler was connected to the finished signal on the AudioStreamPlayer that restarted the stream.
Instead, set the loop property on the imported sample, and remove the signal handler.

Set loop property on OST sample

---

Scene/Game.tscn

The Game scene contains an unused Camera2D, and an unused CanvasLayer named "HUD". Remove both.

Remove unused nodes from Game scene

---

Script/Global.gd

The local "for" iterator variable "name" is shadowing an already-declared
property at the base class "Node".

Global: Fix variable/property shadowing warning

---

Scene/WorldSelector.tscn
Scene/WorldSelector/ExtraWorldSelector.tscn
Scene/WorldSelector/MainWorldSelector.tscn
Script/WorldSelector.gd
Script/WorldSelector/ExtraWorldSelector.gd
Script/WorldSelector/MainWorldSelector.gd
Theme/WorldSelector.tres

Once we have 4 extra worlds, they will not fit vertically into the game window.
Add vertical scrolling. Include the whole page in the scroll, including the back
button and title, so that as many worlds as possible fit. Ensure the focused
button is always in view, so that they can be navigated with a gamepad or arrow
keys.
The scrollbar is set to be 4 pixels wide, and always visible; the right margin
of the page is adjusted to make room for it. This is ugly while we don't need
it, but simpler than trying to hide it when it's not needed.
Fixes https://github.com/endlessm/everlasting-candy/issues/26

Add scrolling to world selector

---

Scene/Goober.tscn

This reverts commit 56406f52932a469e0da33066d33e2a0328f1f586 from https://github.com/endlessm/everlasting-candy/pull/29.
W 0:00:05:0140   Game.gd:7 @ @implicit_new(): res://Scene/Goober.tscn:3 - ext_resource, invalid UID: uid://c5dx3r1l6mwox - using text path instead: res://Script/Goober.gd
<C++ Source>   scene/resources/resource_format_text.cpp:453 @ load()
<Stack Trace>  Game.gd:7 @ @implicit_new()
WorldSelector.gd:42 @ _on_world_button_pressed()
I believe that UIDs for scripts are more a Godot 4.4 thing. I don't know why this one kept being added in my local copy.

Revert "Goober: Add uid for script"

---

Script/Game.gd
Script/Global.gd
Script/Player.gd

Previously, Player would directly call methods on the Game scene instance (accessed via a global variable) when it either stomps on an enemy, or dies.
Instead, emit signals from Player and connect to them from Game to run the same logic.
Since this was the only use of the global variable, remove it.

Player: Emit signals on contact with goobers

---

CandyWrapper/World.tscn
Scene/CandySpawner.tscn
Scene/Game.tscn
Script/CandySpawner.gd
Script/Game.gd
Script/Global.gd
Script/World.gd
Script/WorldSelector.gd
Script/WorldSelector/ExtraWorldSelector.gd
Worlds/Sample/World.tscn

Previously, the top-level scene would either be WorldSelector or Game. To
transition between levels, Game would adjust a global variable containing the
current level number and then reload itself. When Game loads, it accesses that
global variable and instantiates the corresponding map.
This commit introduces a new World scene for each world, using a shared script.
When World is loaded, it loads all levels in its own directory, and then
instantiates the Game scene as a child, setting the first level as its map.
When the player wins or loses a level, Game now emits a signal. In response,
World replaces its child Game scene with a new instance, with the appropriate
map. Game grows a new property to trigger the special behaviour for the first
and last level, rather than checking global …

Introduce World scene for each world

---

Scene/Goober.tscn
Script/Level.gd

Previously, when the Level placed the Goober into the scene, it would apply a 1px vertical offset to its position. This is because the goober is shorter than the 8×8px cell size, so its feet would not touch the floor if it were placed at the vertical centre of the cell.
Instead, apply the same offset inside the Goober scene, to its sprite, hitboxes (why does it have two?) and raycast. Remove the offset from the Level code that places it so that it is placed in the same way as the Player scene.

Goober: add 1px vertical offset

---

doc/GameDesign.md
doc/WorldBuilding.md

The node hierarchy in each level has changed. Also make room to explain the more advanced level creation.
Fixes https://github.com/endlessm/everlasting-candy/issues/34

Docs: Update tile painting level creation

---

Script/Level.gd

The Level script instantiates an explosion when the player and a goober come into contact. The scene to instantiate is stored in an instance variable.
Mark this variable with @export to make it easier to override in the editor, without having to modify or extend the Level script. Switch from load() to preload() since the default path is a constant.
With this change, it is easier to, for example, create a new world where the “explosion” is a shower of magical sparkles rather than an explosion in the violent sense.

Level: Parametrise the Explosion scene

---

Scene/Goober.tscn
Scene/Player.tscn
Script/Level.gd
project.godot

Previously, when the Level script instantiated a Player scene based on a
tile in the TileMapLayer, its signals would be connected to handlers in
the Level class; but it was not easy to connect the signals on a Player
scene that had been instantiated into the level scene in the editor,
because the Player.died signal doesn't include a reference to the
emitting player, which the Level callback needs.
Create a new global group, `player`, and add the Player scene to that
group. Then, in `Level._ready()`, after the TileMapLayer has been
processed, connect to those signals on any members of that group which
are in the tree.
(This preserves the previous behaviour where, if you place two or more
players into the tilemap, they are all "live". I can imagine some
interesting level designs based on …

Use groups for players and goobers

---

Script/Level.gd

Since commit bf38e462 the player signals are connected dynamically by traversing the group. However this fails at runtime with:
"Invalid access to property or key 'died' on a base object of type 'CharacterBody2D'."
This is because signal.connect() is used. That is the preferred way, except it doesn't work dynamically. So use Object.connect() passing the signal StringName instead.

Use Object.connect() for player signals

---

.github/workflows/github-pages.yml

Previously, this project would only be built & published to https://endlessm.github.io/everlasting-candy/ when we make a release or manually run the workflow. This was inherited from the moddable minigames, where we do actually make releases which also get published to the Godot Asset Library.
The primary goal of this project is to add new worlds to explore and stretch the mechanics of the original game. There's real value in having people's contributions be available to play as soon as they are merged, without the ceremony of making a release, and I see no real reason not to.
Adjust the workflow to run on pushes to main, rather than on release.

ci: Publish to GitHub Pages on each push to main

---

Script/World.gd

Consider the following steps:
1. Start world
2. Press jump on title screen to advance from level 0 to level 1
3. On level 1, die
4. During the 1.5-second timeout where “YOU LOSE” is shown, before the
title is re-shown, press jump
The expected result (IMO) is that nothing happens. Once the title screen
is shown again, pressing jump should start level 1 afresh.
But what would previously happen is that the code path for “jump pressed
while on title screen” would be followed, starting level 1. But then
once the 1.5-second timeout is complete, level 1 would be re-started. This
is because `level` is adjusted before the 1.5-second timeout begins.
To fix this, in World's input handler, check the level_type of the
currently-displayed Level, rather than the `level` variable, when
deciding whether …

World: Don't advance to level 1 twice

---

CandyWrapper/World.tscn
Scene/Explosion.tscn
Scene/Player.tscn
Scene/WorldSelector.tscn
Scene/WorldSelector/MainWorldSelector.tscn
Scene/WorldSelector/SettingsPage.tscn
Script/Settings.gd
Script/WorldSelector.gd
Script/WorldSelector/MainWorldSelector.gd
Script/WorldSelector/SettingsPage.gd
Worlds/Cassidy's Purple World/Scene/Explosion.tscn
Worlds/Cassidy's Purple World/Scene/Player.tscn
Worlds/Cassidy's Purple World/World.tscn
Worlds/Sample/World.tscn
default_bus_layout.tres
project.godot

Add two audio buses, Music and Sfx, and assign all audio nodes in the project to the appropriate bus.
Add a Settings page with one slider per bus. Persist the values to a config file, and restore them when the Settings scene is instantiated (which happens when the game is launched).
@Snowsd did the bulk of the work here (thanks!); I applied my review comments from #48 and added code to save & restore the volume levels.

Add Settings page with volume controls

---

CandyWrapper/TileSet.tres
Script/Level.gd
Worlds/Cassidy's Purple World/TileSet.tres

Now that all levels have been converted to use the
TileSetSceneCollectionSource for these actors, we can remove the old static sources from the TileSet.
Notice that the source IDs for the subsequent sources do not change,
which means the TileMapLayer nodes do not need to be updated.
----
This was not part of #68 because we have many learner levels in the wild that will need to be updated, or else they will break when this is merged.
I used https://github.com/endlessm/everlasting-candy/commit/6bada25a4aa8d57bbc44bbcc589586e96ee1b57f to convert all the levels:
1. Apply that patch
2. (Re)open every level (you can use multi-select in the `FileSystem` dock)
3. Save every level (`Ctrl+Shift+Alt+S` or Scene → Save All Scenes)

TileSet: Remove static Player/Goober sprite source 

---

Worlds/Cgm-Dali/World.tscn
Worlds/FelipeWorld/World.tscn

While reviewing/updating these worlds, I didn't notice that they predated the addition of separate audio buses for Music/Sfx so the volume can be controlled.
Add the appropriate buses to the audio nodes in the two worlds.

Cgm-Dali/FelipeWorld: Add audio nodes to correct buses

---

Script/WorldSelector/ExtraWorldSelector.gd

Previously, the order of worlds was based on the directory traversal order.
Instead, use a case-insensitive natural sort. Special-case the Sample world, moving it to the end of the list.

ExtraWorldSelector: Sort worlds, with Sample at the end

---

Scene/Explosion.tscn
Script/CandySpawner.gd
Script/Explosion.gd
Script/Goober.gd
Script/Player.gd
Script/ResourceFinder.gd
Script/World.gd
Worlds/Cassidy's Purple World/World.tscn
doc/WorldBuilding.md

To help build interest in getting to know Godot in an introductory workshop, we want to make it possible to override a world's image assets textures by just placing image files at particular paths in the world's directory, without needing to adjust anything in the editor itself.
Add a helper function which looks up images in a named subdirectory of an Image directory adjacent to the current scene.
Adjust CandySpawner, Player and Goober to use these images, if present, selecting at random if there are more than one. Scale down any alternative Candy images that are too big.
Update the documentation accordingly.

Pick up replacement images from world directory

---

.github/workflows/export.yml
.github/workflows/github-pages.yml

I have [written an action](https://github.com/endlessm/amalgamate-pages) that finds the latest build from each branch, merges them into a single site, and publishes it to GitHub Pages.
Split the current workflow into two, with the following changes:
- `export.yml` unconditionally builds the site for the web (without checking if Pages is enabled), uploads a normal artifact (not a pages artifact), then stops.
- `github-pages.yml` is triggered not by pushes but by the export workflow succeeding (on any branch); it uses the new action to merge the artifacts into a single site and publish it.

Publish all branches to GitHub Pages

---

.github/workflows/github-pages.yml

I put this check into the ancestor of this workflow partly to provide a hint when someone inexperienced with GitHub Actions & Pages tries to reuse the workflow, but mainly to avoid wasting resources building the web version of the game if it's not going to be used.
However, the web version of the game is now built unconditionally in the 'export.yml' workflow. And in practice this check always succeeds; if it fails, the developer setting up the workflow will figure it out. So it is currently just adding ~10 seconds of extra time to the build process for no benefit.
Remove it.

ci: Remove check for whether GitHub Pages is enabled

---

Script/ResourceFinder.gd

Previously, given the following structure:
- World/
- Sparkle Zone/
- Image/
- Candy/
- a.png
- Sweets/
- b.png
- Bonbons/
- c.png
Only a.png would be used. With this change, b.png and c.png will also be used.
Fixes: https://github.com/endlessm/candy-collective/issues/135

Find world assets recursively

---

Script/ResourceFinder.gd
Script/World.gd

This new function, added in Godot 4.4, allows us to remove a pair of workarounds to deal with files being renamed during export.

Use ResourceLoader.list_directory() to find levels and world assets

---

Script/SceneSwitcher.gd
Script/SceneSwitcher.gd.uid
Script/World.gd
Script/WorldSelector.gd
project.godot

Add a global SceneSwitcher node, which replaces direct calls to
SceneTree.change_scene_to_file() in the menu and world code, so that
there is one central location to react to switching between worlds.
Then, when switching to a world, place the path to its directory into
the URL hash. When switching to the main menu, clear the hash. When the
game loads, check if the URL hash contains a valid world path and switch
to it if so.
This allows deep-linking to specific worlds of the game, which learners
may well want to do to share their world with their friends.
One caveat is that in some browsers sound does not work until you first
click on the game or press a key, due to security restrictions. This is
not noticeable in the normal case where the player starts on the main
menu, since the main …

Implement deep-linking to worlds on the web
